bioweb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('genedata.urls')),
    path('admin/', admin.site.urls),
]

genedata/urls.py
from django.urls import path, include
from . import views
from . import api

urlpatterns = [ 
    path('', views.GeneList.as_view(), name='index'), 
    path('gene/<int:pk>', views.GeneDetail.as_view(), name='gene'),
    path('list/<str:type>', views.GeneList.as_view(), name='list'),
    path('poslist/', views.GeneList.as_view(), name='poslist'),
    path('delete/<int:pk>', views.GeneDelete.as_view(), name='delete'),
    path('create_ec/', views.create_ec, name='create'),
    path('create_gene/', views.GeneCreate.as_view(), name='create_gene'),
    path('update/<int:pk>', views.GeneUpdate.as_view(), name='update'),
    path('api/gene/<int:pk>', api.GeneDetail.as_view(), name='gene_api'),  
    path('api/genes/', api.GeneList.as_view(), name='genes_api'),
    ] 

genedata/models.py
from django.db import models  # Import Django's model module

class EC(models.Model):  # Define a model for EC
    ec_name = models.CharField(max_length=256, null=False, blank=False)  # EC name, required field

    def __str__(self): 
        return self.ec_name


class Sequencing(models.Model):  # Define a model for Sequencing
    sequencing_factory = models.CharField(max_length=256, null=False, blank=False)  # Sequencing factory name, required field
    factory_location = models.CharField(max_length=256, null=False, blank=False)  # Factory location, required field

    def __str__(self):
        return self.sequencing_factory


# Create your models here.
class Gene(models.Model):  # Define a model for Gene
    gene_id = models.CharField(max_length=256, null=False, blank=False, db_index=True)  # Gene identifier, required field
    entity = models.CharField(max_length=256, null=False, blank=False)  # Entity name, required field
    start = models.IntegerField(null=False, blank=True)  # Start position, required field but can be blank
    stop = models.IntegerField(null=False, blank=True)  # Stop position, required field but can be blank
    sense = models.CharField(max_length=1)  # Sense strand, single character
    start_codon = models.CharField(max_length=1, default="M")  # Start codon, default is "M"
    sequencing = models.ForeignKey(Sequencing, on_delete=models.DO_NOTHING)  # Foreign key to Sequencing, no action on delete
    ec = models.ForeignKey(EC, on_delete=models.DO_NOTHING)  # Foreign key to EC, no action on delete
    access = models.IntegerField(null=False, blank=False, default=0)  # Access count, required field, default is 0

    def __str__(self): 
        return self.gene_id # Return gene_id as string representation



class Product(models.Model):  # Define a model for Product
    type = models.CharField(max_length=256, null=False, blank=False)  # Product type, required field
    product = models.CharField(max_length=256, null=False, blank=False)  # Product name, required field
    gene = models.ForeignKey(Gene, on_delete=models.CASCADE)  # Foreign key to Gene, cascade delete



class Attribute(models.Model):  # Define a model for Attribute
    key = models.CharField(max_length=256, null=False, blank=False)  # Attribute key, required field
    value = models.CharField(max_length=256, null=False, blank=False)  # Attribute value, required field
    gene = models.ManyToManyField(Gene, through='GeneAttributeLink')  # Many-to-many relationship with Gene through GeneAttributeLink

    def __str__(self):
        return self.key+"="+self.value  # Return key=value as string representation



class GeneAttributeLink(models.Model):  # Define a model for linking Gene and Attribute
    gene = models.ForeignKey(Gene, on_delete=models.DO_NOTHING)  # Foreign key to Gene, no action on delete
    attribute = models.ForeignKey(Attribute, on_delete=models.DO_NOTHING)  # Foreign key to Attribute, no action on delete

genedata/forms.py
from django import forms 
from django.forms import ModelForm
from .models import *

class ECForm(forms.Form): 
    ec_name = forms.CharField(label='EC Name', max_length=100)

    def clean(self): 
        cleaned_data = super(ECForm, self).clean() 
        ec_name = cleaned_data.get("ec_name") 
        if not ec_name.isalpha():
            raise forms.ValidationError("EC Name must contain only alphabetical characters")

class GeneForm(ModelForm): 
    class Meta: 
        model = Gene 
        fields = ['gene_id', 'entity', 'start', 'stop', 'sense', 'start_codon', 'sequencing', 'ec'] 

    def clean(self): 
        cleaned_data = super(GeneForm, self).clean() 
        entity = cleaned_data.get("entity") 
        sense = cleaned_data.get("sense") 
        if not entity == "Chromosome" and not entity == "Plasmid": 
            raise forms.ValidationError("Entity must be 'Chromosome' or 'Plasmid'") 
        if not sense == "+" and not sense == "-": 
            raise forms.ValidationError("Sense must be '+' or '-'") 
        return(cleaned_data)

genedata/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponseRedirect 
from .forms import *
from django.views.generic import ListView 
from django.views.generic import DetailView 
from django.views.generic.edit import CreateView 
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView 


class GeneList(ListView): 
    model = Gene 
    context_object_name = 'master_genes' 
    template_name = 'genedata/index.html'

    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs) 
        context['master_genes'] = Gene.objects.all() 
        
        if "poslist" in self.request.get_full_path():
            context['genes'] = Gene.objects.filter(entity__exact='Chromosome').filter(sense__startswith='+')
        
        if 'type' in self.kwargs: 
            if "Chromosome" in self.kwargs['type'] or "Plasmid" in self.kwargs['type']: 
                context['genes'] = Gene.objects.filter(entity__exact=self.kwargs['type']) 
        return context 
    
    def get_template_names(self): 
        if "poslist" in self.request.get_full_path():
            return 'genedata/list.html'
        if 'type' in self.kwargs: 
            if "Chromosome" in self.kwargs['type'] or "Plasmid" in self.kwargs['type']: 
                return 'genedata/list.html' 
        return 'genedata/index.html'

# Create your views here.
class GeneDetail(DetailView): 
    model = Gene 
    context_object_name = 'gene' 
    template_name = 'genedata/gene.html'

    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs) 
        context['master_genes'] = Gene.objects.all() 
        return context

###### The class above is equivalent to the function below ######
# def gene(request, pk): 
#     gene = Gene.objects.get(pk=pk) 
#     gene.access += 1 
#     print("Gene record:", pk, "access count:", str(gene.access))
#     gene.save()
#     master_genes = Gene.objects.all()
#     return render(request, 'genedata/gene.html', {'gene': gene, 'master_genes': master_genes}) 


class GeneDelete(DeleteView):
    model = Gene
    success_url = "/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['master_genes'] = Gene.objects.all()
        return context
    
# def delete(request, pk): 
#     GeneAttributeLink.objects.filter(gene_id=pk).delete() 
#     Gene.objects.filter(pk=pk).delete()
#     return HttpResponseRedirect("/")  # Redirect to index page

def create_ec(request): 
    master_genes = Gene.objects.all() 
    if request.method == 'POST': 
        form = ECForm(request.POST) 
        if form.is_valid(): 
            ec = EC() 
            ec.ec_name = form.cleaned_data['ec_name'] 
            ec.save() 
            return HttpResponseRedirect('/create_ec/') 
        else:
            return render(request, 'genedata/ec.html', {'error':"failed", 'form': form, 'master_genes': master_genes})
    else: 
        ecs = EC.objects.all() 
        form = ECForm() 
        return render(request, 'genedata/ec.html', {'form': form, 'ecs': ecs, 'master_genes': master_genes})


class GeneCreate(CreateView): 
    model = Gene 
    template_name = 'genedata/create_gene.html' 
    form_class = GeneForm 
    success_url = "/create_gene/" 

    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs) 
        context['master_genes'] = Gene.objects.all() 
        return context 

# def create_gene(request): 
#     master_genes = Gene.objects.all()
#     if request.method == 'POST': 
#         form = GeneForm(request.POST)
#         if form.is_valid(): 
#             gene = form.save()
#             return HttpResponseRedirect('/create_gene/')
#         else: 
#             return render(request, 'genedata/create_gene.html', {'error':"failed", 'form': form, 'master_genes': master_genes})
#     else: 
#         form = GeneForm()
#         master_genes = Gene.objects.all()  
#     return render(request, 'genedata/create_gene.html', {'form': form, 'master_genes': master_genes})

class GeneUpdate(UpdateView): 
    model = Gene 
    fields = ['gene_id', 'entity', 'start', 'stop', 'sense', 'start_codon', 'sequencing', 'ec'] 
    template_name_suffix = '_update_form'
    success_url = "/"

    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs) 
        context['master_genes'] = Gene.objects.all() 
        return context 

genedata/templates/genedata/base.html
{% include "./header.html" %}
{% include "./title.html" %}

<div class="container-fluid">
    <div class="row">
        <div class="col-4" id="gene_list">
            
    {% block geneList %}
    <div id="gene_list">
        <h1>D.Bucha Genes</h1>
        <table>
            <tr>
                <th>Gene ID</th>
            </tr>
            {% for gene in master_genes %}
            <tr>
            <tr>
                <td><a href="/gene/{{gene.pk}}">{{gene}}</a></td>
            </tr>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% endblock %}
    </div>
    
    <div class="col-8" id="content">
        {% block content %}Didn't render content{% endblock %}
    </div>

    {% include "./footer.html" %}
</div>
</div>

genedata/templates/genedata/create_gene.html
{% extends "./base.html" %}
{% load bootstrap4 %}

{% block content %}
<h2>Add New Gene</h2>
<form action="/create_gene/" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Submit">
</form>
{% endblock %}

genedata/templates/genedata/ec.html
{% extends "./base.html" %}
{% load bootstrap4 %}
{% block content %}
<h2>Current EC Names</h2>
<table>
    <tr>
        <th>EC Name</th>
        </th>
        {% for ec in ecs %}
    <tr>
        <td>{{ ec }}</td>
    </tr>
    {% endfor %}
</table>
<br />
<h2>Add New EC Name</h2>
<form action="/create_ec/" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Submit">
</form>
{% endblock%}

genedata/templates/genedata/footer.html
{% load bootstrap4 %}
{% load my_tags %}
<div class="container-fluid">

    <div class="row">
        <div class="col-md-8" id="footer">
    
    <hr>
    <h3>Number of genes: {% gene_count %}</h3>
    <p>Author: {% author_name %} Date: {% todays_date %}.</p>
</div>
</div>
</div>
</body>
</html>

genedata/templates/genedata/gene.html
{% extends './base.html' %}
{% load bootstrap4 %}

{% block content %}
    <h1>{{gene}}</h1>
    <table>
        <tr>
            <th>Key</th><th>Value</th>
        </tr>
        <tr>
            <td>Entity: </td><td>{{gene.entity}}</td>
        </tr>
        <tr>
            <td>Start: </td><td>{{gene.start}}</td>
        </tr>
        <tr>
            <td>Stop: </td><td>{{gene.stop}}</td>
        </tr>
        <tr>
            <td>Sense: </td><td>{{gene.sense}}</td>
        </tr>
        <tr>
            <td>Start Codon: </td><td>{{gene.start_codon}}</td>
        </tr>

    {% with seq=gene.sequencing %}
        <tr>
            <td>Sequencing Factory:</td><td>{{seq.sequencing_factory}}</td>
        </tr>
        <tr>
            <td>Factory Location: </td><td>{{seq.factory_location}}</td>
        </tr>
        {% endwith %}
        {% with ec=gene.ec %}
        <tr>
            <td>EC Name: </td><td>{{ec.ec_name}}</td>
        </tr>
        {% endwith %}
        {% with links=gene.geneattributelink_set.all %}
        {% for link in links %}
        <tr>
            <td>{{link.attribute.key}}</td>
            <td>{{link.attribute.value}}</td>
        </tr>
        {% endfor %}
    {% endwith %}
    </table>


    <a href="/update/{{gene.pk}}">UPDATE RECORD</a>    
    <br/> 
    <a href="/delete/{{gene.pk}}">DELETE RECORD</a> 
    {% endblock %}

genedata/templates/genedata/gene_confirm_delete.html
{% extends "./base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

genedata/templates/genedata/gene_update_form.html
{% extends "./base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}

genedata/templates/genedata/header.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Toy Gene data website">
    <meta name="keywords" content="HTML,gene,genes,advanced,web,development">
    <meta name="author" content="D.Buchan">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" type="text/css" href="../static/css/genedata.css">


    <script>
        function exampleFunction() {

        var x, y, z;
        x = 5;
        y = 6.6;
        z = "hello";
        x = x + y * 2;
        z = z + " world";
        // alert(x);
        console.log(z);
        var test_array = [1, 2, 3];
        var test_hash = { "one": 2, "two": 'this' };
        while (true) {
            console.log("while loop");
            break;
        };
        for (i = 0; i < test_array.length; i++) {
            console.log("array out: " + test_array[i]);
        }
        if (test_array.length === 3) {
            console.log("array is the right length");
        }
        test_array.forEach(function (element) {
            console.log("For Each Output: " + element)
        });
    }

    const changePage = () => {
        console.log("Changing Page");

        var h1_element = document.querySelectorAll("h1");
        var list_panel = document.getElementById("gene_list");
        console.log(list_panel.innerHTML);

        list_panel.innerHTML = "<h1>Aaaaand it's gone</h1>";
        var nav_links = document.getElementsByClassName("nav_link");

        for (var i = 0; i < nav_links.length; i++) {
            nav_links[i].style.color = "black";
        }
        
        for (h in h1_element) {
            h1_element[h].innerHTML = "Changed";
        }
    }
    </script>
</head>

<body>

genedata/templates/genedata/index.html
{% extends './base.html' %}

{% block content %}
    <h2>Select gene location</h2> 
    <a href="/list/Chromosome">Chromosome</a> OR <a href="/list/Plasmid">Plasmid</a>

    <h2>Show positive chromosome Genes</h2>
    <a href="/poslist/">Show This List</a> 
    <br>
    <h2> Create EC Entry</h2>
    <a href="/create_ec/">Add EC entry></a>
    <br>
    <h2>Create Gene Entry</h2> 
    <a href="/create_gene/">Add Gene Entry To DB</a> 
    <br />
{% endblock %}

genedata/templates/genedata/list.html
{% extends './base.html' %}
{% load bootstrap4 %}

{% block content %}    
<h1>Filtered List: {{type}}</h1>
    <table>
        <tr>
            <th>Gene ID</th>
        </tr>
        {% for gene in genes %}
        <tr>
            <tr><td><a href="/gene/{{gene.pk}}" >{{gene}}</a></td></tr> 
        </tr>
        {% endfor %}
    </table>
{% endblock %}

genedata/templates/genedata/master.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description" content="GeneData">
    <meta name="author" content="Paffcio">
    <meta name="keywords" content="GeneData, gene, data, bioinformatics">
    <title>GeneData</title>
    <link rel="stylesheet" href="css/style.css">
</head>

<body>
    <div id="header">
        <img src="https://upload.wikimedia.org/wikipedia/commons/e/e0/202002_La
             boratory_instrument_dna.svg" alt="dna logo" width="50px" height="50px">
        <h1>Gene Browser</h1>
    </div>

    <div id="navigation">
        <a href="/">Home</a>
    </div>

    <div id="content">
        <p>This is some holder content before we develop the
            application</p>
    </div>

    <div id="footer">
        <hr>
        <p>Author: D. Buchan. Date: 23rd April.</p>
    </div>
</body>

</html>

genedata/templates/genedata/title.html
<nav class="navbar navbar-expand-md sticky-top flex-column">
    <div class="w-100 d-flex">
        <div class="navbar-header" id="header">
            <img id="logo"
                src="https://media.istockphoto.com/id/1211484412/vector/gen-dna-blue-logo-vector.jpg?s=612x612&w=0&k=20&c=yvFzmvwsvy7E6cJHvVnksQ6DWv4xo4L7vjjtQ8grLWg=">
            <h1 id="application_title">Gene Browser</h2>
        </div>
    </div>

    <div class="navbar-header" id="header">
        <div class="w-100 d-flex">
            <ul class="navbar-nav mr-auto" id="navigation">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="https://www.ebi.ac.uk/">EBI <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="https://www.uniprot.org/">Uniprot <span
                            class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
</nav>

<!-- <div id="navigation">
    <a class="nav_link" href="/">Home</a> 
    <a class="nav_link" href="https://www.google.com">EBI</a> 
    <a class="nav_link" href="https://www.wp.pl">Uniprot</a> 
</div> -->